apiVersion: v1
kind: Service
metadata:
  # name: {{ include "kvs.fullname" . }}
  name: kvs01
  labels:
    {{- include "kvs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      # nodePort: 30111
  selector:
    {{- include "kvs.selectorLabels" . | nindent 4 }}


