apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: "{{ .Values.metadata.jaeger }}"
spec:
  strategy: "{{ .Values.spec.jaeger }}"
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
