name: deploy-golru

on:
  push:
    branches: 
      - main
    paths:
      - 'golru/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd golru/pkg/storage && go test -v .
      - run: cd golru && docker build -t djedjethai/kvs .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push djedjethai/kvs
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save kvs
      - run: kubectl get deploy kvs01 -o yaml | kubectl replace --force -f -
